name: Publish Package

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🛑 Check Tag
        run: |
          dnf install -y jq
          pkg_version="v$(jq -r .version < package.json)"
          if [[ "${{ github.ref_name }}" != "$pkg_version" ]]; then
              echo "Tag ${{ github.ref_name }} does not match package.json version $pkg_version" >&2
              exit 1
          fi

      - name: 👷 Build Dependencies
        run: |
          dnf install -y make automake gcc gcc-c++ kernel-devel cmake git
          dnf install -y pipewire-devel pipewire-libs pulseaudio-libs-devel pipewire-pulseaudio

      - name: 🍃 Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: 🍃 Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: 🔨 Build
        run: |
          cmake -B build
          cmake --build build

      - name: 🚀 Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: server-arch
          path: build/server

      - name: 🔨 Build
        run: "pnpm install"

      - name: 🛒 Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
